### ISSUE TITLE
Please support jbuilder or maybe just makefile

### ISSUE THREAD

**Issue by dougmencken** [backtracking/ptmap#10]
Because obuild can’t build itself on bytecode-only platforms yet

**Comment by dougmencken** [comment]
I added `jbuild` file

```
(jbuild_version 1)

(library
 ((name ptmap)
  (public_name ptmap)
  (wrapped false)
  (synopsis "implementation of maps over integers implemented as Patricia trees")))
```

and renamed `mv opam ptmap.opam`

and it works

**Comment by UnixJunkie** [comment]
please send a PR, then people have a chance to check if it works and switch easily

**Comment by andyli** [comment]
FYI, https://github.com/ocaml-obuild/obuild/pull/177 fixed obuild on bytecode-only platforms, though there is no new obuild release that includes the fix yet.

**Comment by backtracking** [comment]
obuild is no more used (I switched to dune) so I guess this fixes this issue.
