### ISSUE TITLE
Ptmap.bindings returns unordered list

### ISSUE THREAD

**Issue by andyli** [backtracking/ptmap#11]
According to [the doc](https://caml.inria.fr/pub/docs/manual-ocaml/libref/Map.S.html#VALbindings), `bindings`:

> Return the list of all bindings of the given map. The returned list is sorted in increasing order with respect to the ordering Ord.compare, where Ord is the argument given to Map.Make.

The following code prints the returned list, `4 2 6 1 5 3`, which is unordered:
```ocaml
let list_to_map lst =
  let rec loop l map = match l with
  | [] -> map
  | item :: ls -> loop ls (Ptmap.add item true map)
  in
  loop lst Ptmap.empty

let test_bindings =
  let l, _ = List.split (Ptmap.bindings (list_to_map [3; 1; 2; 4; 6; 5])) in
  List.iter (Printf.printf "%d ") l

let main () =
  test_bindings

let () = main ()
```

**Comment by andyli** [comment]
Other than `bindings`, there are several other methods that should be ordered but ptmap doesn't respect.

After reading the source code and the "Fast Mergeable Integer Maps" paper, I can see that ptmap uses the little-endian encoding, which doesn't provide an easy way to iterate in the key order.

There are 2 ways to go,

 1. Keep it as is and document that ptmap is unordered, contrary to the OCaml Map interface. FYI, there is already a warning about `min_binding` and `max_binding` in `ptmap.mli`.
 2. Switch to using big-endian encoding. However, big-endian encoding provides runtime performance different from the little-endian version.

**Comment by backtracking** [comment]
This is now documented in `ptmap.mli`.
