### ISSUE TITLE
Implement filter_map for OCaml 4.11

### ISSUE THREAD

**Issue by rwmjones** [backtracking/ptmap#16]
Downstream for Fedora I wrote this patch which adds supports for `Map.filter_map`.  It is required for OCaml 4.11.
https://src.fedoraproject.org/rpms/ocaml-ptmap/blob/master/f/ptmap-ocaml-4.11.patch

**Comment by backtracking** [comment]
Thanks for the patch. Just added (commit ea7e4376)
